# https://taskfile.dev

version: "3"

tasks:
  default:
    silent: true
    cmds:
      - cmd: task --list-all

  clean:
    cmds:
      - cmd: rm -rf build
        platforms: [linux]

  config_linux:
    internal: true
    platforms: [linux]
    cmds:
      - cmake -DCMAKE_BUILD_TYPE=Release -B build/Release -S .
    sources:
      - CMakePresets.json
      - CMakeLists.txt
      - src/**/CMakeLists.txt
      - include/**/CMakeLists.txt
      - tests/**/CMakeLists.txt
      - external/**/CMakeLists.txt
      - cmake/**/CMakeLists.txt
    generates:
      - build/Release/compile_commands.json
      - build/compile_commands.json

  config_linux_debug:
    internal: true
    platforms: [linux]
    cmds:
      - cmake -DCMAKE_BUILD_TYPE=Debug -B build/Debug -S .
    sources:
      - CMakePresets.json
      - CMakeLists.txt
      - src/**/CMakeLists.txt
      - include/**/CMakeLists.txt
      - tests/**/CMakeLists.txt
      - external/**/CMakeLists.txt
      - cmake/**/CMakeLists.txt
    generates:
      - build/Debug/compile_commands.json
      - build/compile_commands.json

  config_debug:
    cmds:
      - task: config_linux_debug

  config:
    cmds:
      - task: config_linux

  build_debug:
    cmds:
      - task: config_debug
      - cmd: cmake --build build/Debug

  build:
    cmds:
      - task: config
      - cmd: cmake --build build/Release

  pack:
    cmds:
      - task: build
      - cmd: cd build/Release && cpack -B install -C Release

  test:
    cmds:
      - task: build
      - cmd: ctest --test-dir build/Release/tests --output-on-failure

  run_debug:
    cmds:
      - task: build_debug
      - cmd: build/Debug/src/my_project --config data/config/config.json --debug

  run:
    cmds:
      - task: build
      - cmd: build/Release/src/my_project --config data/config/config.json

  start_openocd:
    cmds:
      - sudo openocd -f interface/cmsis-dap.cfg -c 'set USE_CORE 0' -f target/rp2040.cfg -c "adapter speed 10000"

  start_gdb:
    cmds:
      - ~/.local/xPacks/@xpack-dev-tools/arm-none-eabi-gcc/13.3.1-1.1.1/.content/bin/arm-none-eabi-gdb build/Debug/src/my_project.elf

  start_picocom:
    cmds:
      - sudo picocom --noreset --nolock --omap crlf /dev/ttyACM0 -b 115200

  load_pico:
    cmds:
      - tmuxp load pico.yml

  kill_pico:
    cmds:
      - tmux kill-session -t pico
