version: "3"

tasks:
  default:
    silent: true
    cmds:
      - task --list-all

  gen_config:
    cmds:
      - cue export data/config/config.cue --out json > config.json
    sources:
      - data/config/config.cue

  gen_code:
    cmds:
      - python3 tools/sysml_codegen.py model/*.sysml --output-dir=src/generated --gen-tla
    sources:
      - model/*.sysml
      - tools/sysml_codegen.py

  verify_tla:
    cmds:
      - |
        nix develop -c bash -c '
          cd model/tla
          for spec in *.tla; do
            echo "Verifying $spec..."
            tlc -workers auto "$spec"
          done
        '

  test:
    cmds:
      - cargo check --lib --features pico1

  build_pico1:
    cmds:
      - cargo build --release --features pico1

  build_pico2:
    cmds:
      - cargo build --release --target thumbv8m.main-none-eabihf --features pico2

  clean:
    cmds:
      - cargo clean
      - rm -rf src/generated
